import React from 'react';
import { 
  ArrowRight, 
  CheckCircle2, 
  HeartPulse, 
  Stethoscope, 
  Pill, 
  Baby, 
  Activity, 
  Heart, 
  ShieldCheck, 
  Microscope, 
  UserPlus, 
  Calendar, 
  Clock, 
  User, 
  Mail, 
  Phone, 
  FileText, 
  Check,
  MapPin,
  Search,
  Filter,
  Star,
  Menu,
  X,
  Facebook,
  Twitter,
  Instagram,
  Linkedin,
  Youtube,
  Globe,
  Truck,
  Leaf,
  Droplet,
  Thermometer,
  Syringe,
  FlaskConical,
  Dna,
  Brain,
  Bone,
  Eye,
  Target,
  Ear,
  Smile,
  Frown,
  Meh,
  ThumbsUp,
  ThumbsDown,
  MessageCircle,
  MessageSquare,
  Send,
  Paperclip,
  Image,
  Camera,
  Video,
  Mic,
  MicOff,
  Volume2,
  VolumeX,
  Settings,
  HelpCircle,
  Info,
  AlertCircle,
  AlertTriangle,
  Bell,
  BellOff,
  Lock,
  Unlock,
  Key,
  CreditCard,
  DollarSign,
  ShoppingCart,
  Briefcase,
  File,
  Folder,
  Home,
  Layout,
  Grid,
  List,
  MoreHorizontal,
  MoreVertical,
  Plus,
  Minus,
  Edit,
  Trash,
  RefreshCw,
  Download,
  Upload,
  Share,
  Printer,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  LogOut,
  LogIn,
  Smartphone,
  Monitor,
  Database,
  BarChart3,
  Lightbulb,
  Rocket,
  ArrowUpRight,
  Store,
  HandHeart,
  School,
  Megaphone,
  TrendingUp,
  Ambulance
} from 'lucide-react';

// Additional icons referenced by CMS content but missing in the default map
import { Building, Building2 } from 'lucide-react';
import { Users, GraduationCap, Package } from 'lucide-react';

export const iconMap: Record<string, React.ElementType> = {
  'ArrowRight': ArrowRight,
  'CheckCircle2': CheckCircle2,
  'HeartPulse': HeartPulse,
  'Stethoscope': Stethoscope,
  'Pill': Pill,
  'Baby': Baby,
  'Activity': Activity,
  'Heart': Heart,
  'ShieldCheck': ShieldCheck,
  'Microscope': Microscope,
  'UserPlus': UserPlus,
  'Calendar': Calendar,
  'Clock': Clock,
  'User': User,
  'Mail': Mail,
  'Phone': Phone,
  'FileText': FileText,
  'Check': Check,
  'MapPin': MapPin,
  'Search': Search,
  'Filter': Filter,
  'Star': Star,
  'Menu': Menu,
  'X': X,
  'Facebook': Facebook,
  'Twitter': Twitter,
  'Instagram': Instagram,
  'Linkedin': Linkedin,
  'Youtube': Youtube,
  'Globe': Globe,
  'Truck': Truck,
  'Leaf': Leaf,
  'Droplet': Droplet,
  'Thermometer': Thermometer,
  'Syringe': Syringe,
  'FlaskConical': FlaskConical,
  'Dna': Dna,
  'Brain': Brain,
  'Bone': Bone,
  'Eye': Eye,
  'Target': Target,
  'Ear': Ear,
  'Smile': Smile,
  'Frown': Frown,
  'Meh': Meh,
  'ThumbsUp': ThumbsUp,
  'ThumbsDown': ThumbsDown,
  'MessageCircle': MessageCircle,
  'MessageSquare': MessageSquare,
  'Send': Send,
  'Paperclip': Paperclip,
  'Image': Image,
  'Camera': Camera,
  'Video': Video,
  'Mic': Mic,
  'MicOff': MicOff,
  'Volume2': Volume2,
  'VolumeX': VolumeX,
  'Settings': Settings,
  'HelpCircle': HelpCircle,
  'Info': Info,
  'AlertCircle': AlertCircle,
  'AlertTriangle': AlertTriangle,
  'Bell': Bell,
  'BellOff': BellOff,
  'Lock': Lock,
  'Unlock': Unlock,
  'Key': Key,
  'CreditCard': CreditCard,
  'DollarSign': DollarSign,
  'ShoppingCart': ShoppingCart,
  'Briefcase': Briefcase,
  'File': File,
  'Folder': Folder,
  'Home': Home,
  'Layout': Layout,
  'Grid': Grid,
  'List': List,
  'MoreHorizontal': MoreHorizontal,
  'MoreVertical': MoreVertical,
  'Plus': Plus,
  'Minus': Minus,
  'Edit': Edit,
  'Trash': Trash,
  'RefreshCw': RefreshCw,
  'Download': Download,
  'Upload': Upload,
  'Share': Share,
  'Printer': Printer,
  'ChevronRight': ChevronRight,
  'ChevronLeft': ChevronLeft,
  'ChevronDown': ChevronDown,
  'ChevronUp': ChevronUp,
  'ExternalLink': ExternalLink,
  'LogOut': LogOut,
  'LogIn': LogIn,
  'Smartphone': Smartphone,
  'Monitor': Monitor,
  'Database': Database,
  'BarChart3': BarChart3,
  'Lightbulb': Lightbulb,
  'Rocket': Rocket,
  'ArrowUpRight': ArrowUpRight,
  'Store': Store,
  'HandHeart': HandHeart,
  'School': School,
  'Megaphone': Megaphone,
  'TrendingUp': TrendingUp,
  'Ambulance': Ambulance,
  // CMS-specific additions
  'Building': Building,
  'Building2': Building2,
  'Users': Users,
  'GraduationCap': GraduationCap,
  'Package': Package
};

export const getIcon = (name: string | undefined): React.ElementType | null => {
  if (!name) return null;
  // Try direct match
  if (iconMap[name]) return iconMap[name];
  
  const normalize = (s: string) => s.toLowerCase().replace(/[-_]/g, '');
  const target = normalize(name);
  const key = Object.keys(iconMap).find(k => normalize(k) === target);
  return key ? iconMap[key] : null;
};
